export const LOAD_EMPLOYEE = "LOAD_EMPLOYEE";
export const LOAD_EMPLOYEE_SUCCES = "LOAD_EMPLOYEE_SUCCES";
export const LOAD_EMPLOYEE_ERROR = "LOAD_EMPLOYEE_ERROR";

export const ADD_EMPLOYEE = "ADD_EMPLOYEE";
